#!/bin/bash

logoutvolume="/Library/LogHook/nobootsound_logoutvol"

# Store the volume right before shutdown
osascript -e 'output volume of (get volume settings)' > "$logoutvolume"
read val < "$logoutvolume"

logger "Nobootsound. Volume muted before shutdown: $val"

# Lower volume, so that soft sound will be played at boot; replacing 5 with 15 is recommended on laptops, as 5 is barely audible.
osascript -e 'set volume output volume 5 --100%'
