#!/bin/bash

# Read the value stored in .nobootsound_logoutvol to determine the volume
# before shutdown
logoutvolume="/Library/LogHook/nobootsound_logoutvol"
read val < "$logoutvolume"
logger "Nobootsound restoring volume to previous value. % volume: $val"

osascript -e "set volume output volume $val --100%"
